read:
  replicas: 1
  persistence:
    storageClass: standard
write:
  replicas: 1
  persistence:
    storageClass: standard
backend:
  replicas: 1
  persistence:
    storageClass: standard
loki:
  schemaConfig:
    configs:
      - from: 2024-08-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
        chunks:
          period: 24h
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames: # First of all, create these two buckets inside minio
      chunks: loki-chunks
      ruler: loki-ruler
    type: s3
    s3:
      endpoint: http://minio-local:9000 # This is just an example, change the url with your own minio instance
      secretAccessKey: <<CHANGEME>>
      accessKeyId: <<CHANGEME>>
      insecure: true
      s3ForcePathStyle: true
      region: <<CHANGEME>>
