monitoring:
  selfMonitoring:
    grafanaAgent:
      installOperator: false
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
singleBinary:
  replicas: 1
